### ISSUE TITLE
DB doesn't exist

### ISSUE THREAD

**Issue by florioro** [stuntcoders/stunt_mage_simple_menu#1]
Hello,

I upload all folders to website, I clear cache and I select Simple menu from CMS menu and I see following error mesage:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'rcra3426_bikestore.stuntcoders_simplemenu' doesn't exist

Please tell me where I made mistake?

**Comment by florioro** [comment]
Sorry, I solved, everything it's Ok, Is not cleared all cache...

**Comment by iodic** [comment]
Yes, that's usually an issue. :)

Thanks for reaching out and enjoy the module!
